name: meals_calories_tracker
description: A modern meal calories tracker app with beautiful UI and analytics
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # UI & Theme
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  fl_chart: ^0.67.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  uuid: ^4.3.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
